import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pallete Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Pallete Gen</h1>
        
        <div className='input'>
          <label htmlFor='file'>Upload Image</label>
          <input type='file' id='file' />
        </div>
      </header>
      <main className={styles.main}>
        
      </main>
    </>
  )
}
